pack_name = "forge-1.20.1-tech-n-adventure-stuff"
mc_version = "1.20.1"
modloader = "Forge"
default_providers = ["Modrinth"]
forbidden_mods = ["fabric-api"]

[mods.adaptive-performance-tweaks-core]
name = "adaptive-performance-tweaks-core"
version = "*"
server_side = true
client_side = true

[mods.adaptive-performance-tweaks-items]
name = "adaptive-performance-tweaks-items"
version = "*"
server_side = true
client_side = true

[mods.advanced-backups]
name = "advanced-backups"
version = "*"
server_side = true
client_side = true

[mods.ae2]
name = "ae2"
version = "*"

[mods.aether]
name = "aether"
version = "*"

[mods.ai-improvements]
name = "ai-improvements"
version = "*"
server_side = true
client_side = true

[mods.akashic-tome]
name = "akashic-tome"
version = "*"

[mods.alekiships]
name = "alekiships"
version = "*"

[mods.alexs-caves]
name = "alexs-caves"
version = "*"

[mods.alexs-mobs]
name = "alexs-mobs"
version = "*"

[mods.almost-unified]
name = "almost-unified"
version = "*"

[mods.alternate-current]
name = "alternate-current"
version = "*"

[mods.appleskin]
name = "appleskin"
version = "*"

[mods.applied-botanics]
name = "applied-botanics"
version = "*"

[mods.aquamirae]
name = "aquamirae"
version = "*"

[mods.athena-ctm]
name = "athena-ctm"
version = "*"

[mods.badoptimizations]
name = "badoptimizations"
version = "*"

[mods.better-archeology]
name = "better-archeology"
version = "*"

[mods.betterf3]
name = "betterf3"
version = "*"

[mods.block-runner]
name = "block-runner"
version = "*"

[mods.botania]
name = "botania"
version = "*"

[mods.caelus]
name = "caelus"
version = "*"

[mods.cc-tweaked]
name = "cc-tweaked"
version = "*"

[mods.cc-vs]
name = "cc-vs"
version = "*"
server_side = true
client_side = true

[mods.cccbridge]
name = "cccbridge"
version = "*"

[mods.chunky]
name = "chunky"
version = "*"

[mods.clumps]
name = "clumps"
version = "*"

[mods.connector]
name = "connector"
version = "*"

[mods.connector-extras]
name = "connector-extras"
version = "*"

[mods.continents]
name = "continents"
version = "*"

[mods.controlling]
name = "controlling"
version = "*"

[mods.copycats]
name = "copycats"
version = "*"

[mods.crafting-tweaks]
name = "crafting-tweaks"
version = "*"

[mods.crafttweaker]
name = "crafttweaker"
version = "*"

[mods.create]
name = "create"
version = "*"

[mods.create-applied-kinetics]
name = "create-applied-kinetics"
version = "*"

[mods.create-big-cannons]
name = "create-big-cannons"
version = "*"

[mods.create-central-kitchen]
name = "create-central-kitchen"
version = "*"

[mods.create-clockwork]
name = "create-clockwork"
version = "*"

[mods.create-connected]
name = "create-connected"
version = "*"

[mods.create-deco]
name = "create-deco"
version = "*"

[mods.create-diesel-generators]
name = "create-diesel-generators"
version = "*"

[mods.create-enchantment-industry]
name = "create-enchantment-industry"
version = "*"

[mods.create-let-the-adventure-begin]
name = "create-let-the-adventure-begin"
version = "*"
server_side = true
client_side = true

[mods.create-new-age]
name = "create-new-age"
version = "*"

[mods.create-structures]
name = "create-structures"
version = "*"

[mods.create-structures-arise]
name = "create-structures-arise"
version = "*"

[mods.create-teleporters]
name = "create-teleporters"
version = "*"

[mods.create-wizardry]
name = "create-wizardry"
version = "*"

[mods.createaddition]
name = "createaddition"
version = "*"

[mods.cubes-without-borders]
name = "cubes-without-borders"
version = "*"

[mods.drive-by-wire]
name = "drive-by-wire"
version = "*"

[mods.dungeon-now-loading]
name = "dungeon-now-loading"
version = "*"

[mods.dungeons_delight]
name = "dungeons_delight"
version = "*"

[mods.effortless]
name = "effortless"
version = "*"

[mods.embeddium]
name = "embeddium"
version = "*"

[mods.emi]
name = "emi"
version = "*"

[mods.emi-loot]
name = "emi-loot"
version = "*"

[mods.emi-ores]
name = "emi-ores"
version = "*"

[mods.emienchants]
name = "emienchants"
version = "*"

[mods.emiffect]
name = "emiffect"
version = "*"

[mods.enderio]
name = "enderio"
version = "*"

[mods.entityculling]
name = "entityculling"
version = "*"

[mods.every-compat]
name = "every-compat"
version = "*"

[mods.farmers-delight]
name = "farmers-delight"
version = "*"

[mods.ferrite-core]
name = "ferrite-core"
version = "*"

[mods.functional-storage]
name = "functional-storage"
version = "*"

[mods.gravestone-mod]
name = "gravestone-mod"
version = "*"

[mods.hardcore-revival]
name = "hardcore-revival"
version = "*"

[mods.hypertube]
name = "hypertube"
version = "*"

[mods.immediatelyfast]
name = "immediatelyfast"
version = "*"

[mods.immersive-aircraft]
name = "immersive-aircraft"
version = "*"

[mods.immersive-melodies]
name = "immersive-melodies"
version = "*"

[mods.invmove]
name = "invmove"
version = "*"

[mods.iris-flw-compat]
name = "iris-flw-compat"
version = "*"

[mods.irons-spells-n-spellbooks]
name = "irons-spells-n-spellbooks"
version = "*"

[mods.item-obliterator]
name = "item-obliterator"
version = "*"

[mods.jade]
name = "jade"
version = "*"

[mods.jade-vs]
name = "jade-vs"
version = "*"

[mods.jei]
name = "jei"
version = "*"
server_side = true
client_side = true

[mods.l_enders-cataclysm]
name = "l_enders-cataclysm"
version = "*"

[mods.leaves-be-gone]
name = "leaves-be-gone"
version = "*"
server_side = true
client_side = true

[mods.lithostitched]
name = "lithostitched"
version = "*"
server_side = true
client_side = true

[mods.mariums-soulslike-weaponry]
name = "mariums-soulslike-weaponry"
version = "*"

[mods.memoryleakfix]
name = "memoryleakfix"
version = "*"

[mods.miners-delight]
name = "miners-delight"
version = "*"

[mods.mouse-tweaks]
name = "mouse-tweaks"
version = "*"

[mods.mowzies-mobs]
name = "mowzies-mobs"
version = "*"

[mods.natures-compass]
name = "natures-compass"
version = "*"

[mods.noisium]
name = "noisium"
version = "*"

[mods.observable]
name = "observable"
version = "*"

[mods.oculus]
name = "oculus"
version = "*"

[mods.patchouli]
name = "patchouli"
version = "*"

[mods.pehkui]
name = "pehkui"
version = "*"

[mods.ping-wheel]
name = "ping-wheel"
version = "*"

[mods.playeranimator]
name = "playeranimator"
version = "*"

[mods.projectile-damage-attribute]
name = "projectile-damage-attribute"
version = "3.2.2+1.20.1-forge"

[mods.quark]
name = "quark"
version = "*"

[mods.regions-unexplored]
name = "regions-unexplored"
version = "*"

[mods.repurposed-structures-forge]
name = "repurposed-structures-forge"
version = "*"

[mods.rubidium-extra]
name = "rubidium-extra"
version = "*"

[mods.rustic-engineer]
name = "rustic-engineer"
version = "*"

[mods.schematic-energistics]
name = "schematic-energistics"
version = "*"

[mods.simple-discord-rpc]
name = "simple-discord-rpc"
version = "4.0.4"

[mods.slice-and-dice]
name = "slice-and-dice"
version = "*"

[mods.sophisticated-backpacks]
name = "sophisticated-backpacks"
version = "*"

[mods.sophisticated-backpacks-create-integration]
name = "sophisticated-backpacks-create-integration"
version = "*"

[mods.spark]
name = "spark"
version = "*"

[mods.spectrum]
name = "spectrum"
version = "1.8.11"
loader = "Fabric"

[mods.tcintegrations]
name = "tcintegrations"
version = "*"

[mods.tectonic]
name = "tectonic"
version = "2.4.1"

[mods.thermal-expansion]
name = "thermal-expansion"
version = "*"

[mods.thermal-integration]
name = "thermal-integration"
version = "*"

[mods.tinkers-construct]
name = "tinkers-construct"
version = "*"

[mods.trackwork]
name = "trackwork"
version = "*"

[mods.twilightforest]
name = "twilightforest"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/5468/648/twilightforest-1.20.1-4.3.2508-universal.jar"
server_side = true
client_side = true

[mods.xaeros-minimap]
name = "xaeros-minimap"
version = "*"

[mods.xaeros-world-map]
name = "xaeros-world-map"
version = "*"

[files."./client/config/cubes_without_borders.json"]
target_path = "config/cubes_without_borders.json"
side = "Client"
apply_policy = "Once"

[files."./client/config/xaerominimap.txt"]
target_path = "config/xaerominimap.txt"
side = "Client"
apply_policy = "Once"

[files."./client/options.txt"]
target_path = "options.txt"
side = "Client"
apply_policy = "Once"

[files."./client/resourcepacks/Faithful 32x - 1.20.1.zip"]
target_path = "resourcepacks/Faithful 32x - 1.20.1.zip"
side = "Client"
apply_policy = "Always"

[files."./client/resourcepacks/Twilight JAPPA Pack 1.0.0.zip"]
target_path = "resourcepacks/Twilight JAPPA Pack 1.0.0.zip"
side = "Client"
apply_policy = "Always"

[files."./client/servers.dat"]
target_path = "servers.dat"
side = "Client"
apply_policy = "Once"

[files."./client/shaderpacks/ComplementaryReimagined_r5.6.1.zip"]
target_path = "shaderpacks/ComplementaryReimagined_r5.6.1.zip"
side = "Client"
apply_policy = "Always"

[files."./common/config/Weather2"]
target_path = "config/Weather2"
side = "Both"
apply_policy = "Always"

[files."./common/config/aiimprovements-common.toml"]
target_path = "config/aiimprovements-common.toml"
side = "Both"
apply_policy = "Always"

[files."./common/config/createappliedkinetics-common.toml"]
target_path = "config/createappliedkinetics-common.toml"
side = "Both"
apply_policy = "Always"

[files."./common/config/effortless.toml"]
target_path = "config/effortless.toml"
side = "Both"
apply_policy = "Always"

[files."./common/config/item_obliterator.json5"]
target_path = "config/item_obliterator.json5"
side = "Both"
apply_policy = "Always"

[files."./common/config/lithium.properties"]
target_path = "config/lithium.properties"
side = "Both"
apply_policy = "Always"

[files."./common/scripts/raw_redstone_block.zs"]
target_path = "scripts/raw_redstone_block.zs"
side = "Both"
apply_policy = "Always"

[files."./server/config/AdvancedBackups.properties"]
target_path = "config/AdvancedBackups.properties"
side = "Server"
apply_policy = "Always"

[files."./server/config/carryon-common.toml"]
target_path = "config/carryon-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/config/iceandfire-common.toml"]
target_path = "config/iceandfire-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/config/rats-common.toml"]
target_path = "config/rats-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/server.properties"]
target_path = "server.properties"
side = "Server"
apply_policy = "Always"

[files."./server/tech-n-adventure-stuff/serverconfig"]
target_path = "tech-n-adventure-stuff/serverconfig"
side = "Server"
apply_policy = "Always"

[files."./server/whitelist.json"]
target_path = "whitelist.json"
side = "Server"
apply_policy = "Always"
