pack_name = "forge-1.20.1-tech-n-adventure-stuff"
mc_version = "1.20.1"
modloader = "Forge"
default_providers = ["Modrinth"]
forbidden_mods = ["fabric-api"]

[mods.advanced-backups]
name = "advanced-backups"
version = "*"
server_side = true
client_side = true

[mods.ae2]
name = "ae2"
version = "*"

[mods.aether]
name = "aether"
version = "*"

[mods.akashic-tome]
name = "akashic-tome"
version = "*"

[mods.alekiships]
name = "alekiships"
version = "*"

[mods.alexs-caves]
name = "alexs-caves"
version = "*"

[mods.alexs-mobs]
name = "alexs-mobs"
version = "*"

[mods.almost-unified]
name = "almost-unified"
version = "*"

[mods.alternate-current]
name = "alternate-current"
version = "*"

[mods.appleskin]
name = "appleskin"
version = "*"

[mods.aquamirae]
name = "aquamirae"
version = "*"

[mods.ars-additions]
name = "ars-additions"
version = "*"

[mods.ars-creo]
name = "ars-creo"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/6265/696/ars_creo-1.20.1-4.3.0.jar"
server_side = true
client_side = true

[mods.ars-energistique]
name = "ars-energistique"
version = "*"

[mods.ars-nouveau]
name = "ars-nouveau"
version = "*"

[mods.ars-scalaes]
name = "ars-scalaes"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/5850/815/ars_scalaes-1.20.1-1.10.7c.jar"
server_side = true
client_side = true

[mods.arsdelight]
name = "arsdelight"
version = "*"

[mods.badoptimizations]
name = "badoptimizations"
version = "*"

[mods.better-archeology]
name = "better-archeology"
version = "*"

[mods.betterf3]
name = "betterf3"
version = "*"

[mods.block-runner]
name = "block-runner"
version = "*"

[mods.c2me-fabric]
name = "c2me-fabric"
version = "*"
loader = "Fabric"

[mods.caelus]
name = "caelus"
version = "*"

[mods.canary]
name = "canary"
version = "*"

[mods.chunky]
name = "chunky"
version = "*"

[mods.clumps]
name = "clumps"
version = "*"

[mods.connector]
name = "connector"
version = "*"

[mods.connector-extras]
name = "connector-extras"
version = "*"

[mods.controlling]
name = "controlling"
version = "*"

[mods.copycats]
name = "copycats"
version = "*"

[mods.crafting-tweaks]
name = "crafting-tweaks"
version = "*"

[mods.create]
name = "create"
version = "*"

[mods.create-applied-kinetics]
name = "create-applied-kinetics"
version = "*"

[mods.create-central-kitchen]
name = "create-central-kitchen"
version = "*"

[mods.create-connected]
name = "create-connected"
version = "*"

[mods.create-enchantment-industry]
name = "create-enchantment-industry"
version = "*"

[mods.create-new-age]
name = "create-new-age"
version = "*"

[mods.create-structures]
name = "create-structures"
version = "*"

[mods.create-structures-arise]
name = "create-structures-arise"
version = "*"

[mods.create-teleporters]
name = "create-teleporters"
version = "*"

[mods.createaddition]
name = "createaddition"
version = "*"

[mods.cubes-without-borders]
name = "cubes-without-borders"
version = "*"

[mods.dungeon-now-loading]
name = "dungeon-now-loading"
version = "*"

[mods.dungeons_delight]
name = "dungeons_delight"
version = "*"

[mods.effortless-building]
name = "effortless-building"
version = "*"

[mods.embeddium]
name = "embeddium"
version = "*"

[mods.emi]
name = "emi"
version = "*"

[mods.emi-loot]
name = "emi-loot"
version = "*"

[mods.emi-ores]
name = "emi-ores"
version = "*"

[mods.emienchants]
name = "emienchants"
version = "*"

[mods.emiffect]
name = "emiffect"
version = "*"

[mods.enderio]
name = "enderio"
version = "*"

[mods.entityculling]
name = "entityculling"
version = "*"

[mods.farmers-delight]
name = "farmers-delight"
version = "*"

[mods.ferrite-core]
name = "ferrite-core"
version = "*"

[mods.functional-storage]
name = "functional-storage"
version = "*"

[mods.gravestone-mod]
name = "gravestone-mod"
version = "*"

[mods.hardcore-revival]
name = "hardcore-revival"
version = "*"

[mods.hypertube]
name = "hypertube"
version = "*"

[mods.idas]
name = "idas"
version = "*"

[mods.immediatelyfast]
name = "immediatelyfast"
version = "*"

[mods.immersive-aircraft]
name = "immersive-aircraft"
version = "*"

[mods.immersive-melodies]
name = "immersive-melodies"
version = "*"

[mods.invmove]
name = "invmove"
version = "*"

[mods.iris-flw-compat]
name = "iris-flw-compat"
version = "*"

[mods.item-obliterator]
name = "item-obliterator"
version = "*"

[mods.jade]
name = "jade"
version = "*"

[mods.jei]
name = "jei"
version = "*"
server_side = true
client_side = true

[mods.l_enders-cataclysm]
name = "l_enders-cataclysm"
version = "*"

[mods.legendary-monsters]
name = "legendary-monsters"
version = "*"

[mods.lithostitched]
name = "lithostitched"
version = "*"
server_side = true
client_side = true

[mods.mariums-soulslike-weaponry]
name = "mariums-soulslike-weaponry"
version = "*"

[mods.memoryleakfix]
name = "memoryleakfix"
version = "*"

[mods.miners-delight]
name = "miners-delight"
version = "*"

[mods.mobtimizations]
name = "mobtimizations"
version = "*"

[mods.modernfix]
name = "modernfix"
version = "*"
server_side = true
client_side = true

[mods.mouse-tweaks]
name = "mouse-tweaks"
version = "*"

[mods.mowzies-mobs]
name = "mowzies-mobs"
version = "*"

[mods.natures-compass]
name = "natures-compass"
version = "*"

[mods.noisium]
name = "noisium"
version = "*"

[mods.oculus]
name = "oculus"
version = "*"

[mods.patchouli]
name = "patchouli"
version = "*"

[mods.pehkui]
name = "pehkui"
version = "*"

[mods.playeranimator]
name = "playeranimator"
version = "*"

[mods.projectile-damage-attribute]
name = "projectile-damage-attribute"
version = "3.2.2+1.20.1-forge"

[mods.regions-unexplored]
name = "regions-unexplored"
version = "*"

[mods.rubidium-extra]
name = "rubidium-extra"
version = "*"

[mods.rustic-engineer]
name = "rustic-engineer"
version = "*"

[mods.servercore]
name = "servercore"
version = "*"

[mods.simple-discord-rpc]
name = "simple-discord-rpc"
version = "*"

[mods.slice-and-dice]
name = "slice-and-dice"
version = "*"

[mods.sophisticated-backpacks]
name = "sophisticated-backpacks"
version = "*"

[mods.sophisticated-backpacks-create-integration]
name = "sophisticated-backpacks-create-integration"
version = "*"

[mods.spark]
name = "spark"
version = "*"

[mods.tcintegrations]
name = "tcintegrations"
version = "*"

[mods.tectonic]
name = "tectonic"
version = "*"

[mods.thermal-expansion]
name = "thermal-expansion"
version = "*"

[mods.thermal-integration]
name = "thermal-integration"
version = "*"

[mods.tinkers-construct]
name = "tinkers-construct"
version = "*"

[mods.twilightforest]
name = "twilightforest"
version = "*"
providers = ["Raw"]
download_url = "https://mediafilez.forgecdn.net/files/5468/648/twilightforest-1.20.1-4.3.2508-universal.jar"
server_side = true
client_side = true

[mods.xaeros-minimap]
name = "xaeros-minimap"
version = "*"

[mods.xaeros-world-map]
name = "xaeros-world-map"
version = "*"

[files."./client/config/cubes_without_borders.json"]
target_path = "config/cubes_without_borders.json"
side = "Client"
apply_policy = "Once"

[files."./client/config/xaerominimap.txt"]
target_path = "config/xaerominimap.txt"
side = "Client"
apply_policy = "Once"

[files."./client/options.txt"]
target_path = "options.txt"
side = "Client"
apply_policy = "Once"

[files."./client/resourcepacks/Faithful 32x - 1.20.1.zip"]
target_path = "resourcepacks/Faithful 32x - 1.20.1.zip"
side = "Client"
apply_policy = "Always"

[files."./client/resourcepacks/Twilight JAPPA Pack 1.0.0.zip"]
target_path = "resourcepacks/Twilight JAPPA Pack 1.0.0.zip"
side = "Client"
apply_policy = "Always"

[files."./client/servers.dat"]
target_path = "servers.dat"
side = "Client"
apply_policy = "Once"

[files."./client/shaderpacks/ComplementaryReimagined_r5.6.1.zip"]
target_path = "shaderpacks/ComplementaryReimagined_r5.6.1.zip"
side = "Client"
apply_policy = "Always"

[files."./common/config/canary.properties"]
target_path = "config/canary.properties"
side = "Both"
apply_policy = "Always"

[files."./server/config/AdvancedBackups.properties"]
target_path = "config/AdvancedBackups.properties"
side = "Server"
apply_policy = "Always"

[files."./server/config/carryon-common.toml"]
target_path = "config/carryon-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/config/iceandfire-common.toml"]
target_path = "config/iceandfire-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/config/rats-common.toml"]
target_path = "config/rats-common.toml"
side = "Server"
apply_policy = "Always"

[files."./server/server.properties"]
target_path = "server.properties"
side = "Server"
apply_policy = "Always"

[files."./server/whitelist.json"]
target_path = "whitelist.json"
side = "Server"
apply_policy = "Always"
