# This is the configuration file for Radium.
# This file exists for debugging purposes and should not be configured otherwise.
#
# You can find information on editing this file and all the available options here:
# https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File
#
# By default, this file will be empty except for this notice.

# C2M2-fabric in connector crashes with canary.
# Found this workaround in https://github.com/AbdElAziz333/Canary/issues/231
mixin.alloc.nbt=false
mixin.chunk.replace_streams=false

# vs2 conflicts with canary poi optimisations
mixin.ai.poi=false